---
title: Sarah Winton Design
timezone: America/Los_Angeles
description: 'Sarah Winton Design: Graphic Designer'
author:
  name: Sarah Winton Design
  twitter: sarahwinton
favicon:
ga_tracking_id: UA-103655965-1
image: '/uploads/2018/10/15/logo.png'
lang: en
logo: '/uploads/2018/10/15/logo.png'
social:
  name: Sarah Winton Design
  links:
    - https://twitter.com/sarahwinton
    - https://www.facebook.com/sarahwintondesign
    - https://www.linkedin.com/in/sarah-winton
    - https://github.com/sarahwintondesign.com
twitter:
  username: sarahwinton
url: https://sarahwintondesign.com
baseurl:
collections:
  work:
    title: Work
    output: true
defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: page
  - scope:
      path: ''
      type: work
    values:
      layout: page
exclude:
  - README.md
  - package.json
  - package-lock.json
kramdown:
  show_warnings: true
liquid:
  error_mode: strict
  strict_filters: true
permalink: pretty
remote_theme: codytwinton/portfolio-theme@v0.11.0
safe: true
sass:
  style: compressed
strict_front_matter: true
titles_from_headings:
  enabled: false
  strip_title: false
  collections: false
copyright: Copyright © 2019 Sarah Winton Design
