---
title: Sarah Winton Design
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: sarah@sarahwintondesign.com
tagline: Telling Stories and Creating Beauty
description: 'Graphic Designer in Birmingham, AL

'
baseurl: ''
url: http://sarahwintondesign.com
current-work:
  title: Current Work
  link: http://emilywellsdesign.com
contact-me:
  title: Contact Me
  link: mailto:sarah@sarahwintondesign.com
social:
  facebook: sarahwintondesign
  twitter: sarahwinton
  instagram: sarahwintondesign
  medium: sarahwinton
  linked-in: sarah-winton
  github: sarahwintondesign
markdown: kramdown
plugins:
- jekyll-feed
