---
title: Sarah Winton Design
timezone: America/Los_Angeles
url: https://sarahwintondesign.com
ga_tracking_id: UA-103655965-1
baseurl: 
kramdown:
  show_warnings: true
lang: en
liquid:
  error_mode: strict
  strict_filters: true
permalink: pretty
remote_theme: codytwinton/portfolio-theme@v0.9.0
safe: true
sass:
  style: compressed
strict_front_matter: true
collections:
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: work
  values:
    layout: page
description: 'Sarah Winton Design: Graphic Designer'
author:
  name: Sarah Winton Design
  twitter: sarahwinton
social:
  name: Sarah Winton Design
  links:
  - https://twitter.com/sarahwinton
  - https://www.facebook.com/sarahwintondesign
  - https://www.linkedin.com/in/sarah-winton
  - https://github.com/sarahwintondesign.com
twitter:
  username: sarahwinton
titles_from_headings:
  enabled: false
  strip_title: false
  collections: false
image: ''
logo: ''
