---
title: Sarah Winton Design
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    subtitle: 
    hero_image: "/uploads/hero.jpg"
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    subtitle: 
- scope:
    path: ''
    type: work
  values:
    display_title: 
    subtitle: 
    profiles:
      website: 
      facebook: 
    images: 
    - 
url: http://sarahwintondesign.com
email: sarah@sarahwintondesign.com
description: 'Graphic Designer in Birmingham, AL

'
google_analytics:
  prod_key: UA-103655965-1
  staging_key: testing
social:
  facebook: sarahwintondesign
  twitter: sarahwinton
  instagram: sarahwintondesign
  medium: sarahwinton
  linked-in: sarah-winton
  github: sarahwintondesign
baseurl: 
markdown: kramdown
permalink: pretty
gems:
- jekyll-feed
- jekyll-redirect-from
