---
title: Sarah Winton Design
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: http://sarahwintondesign.com
email: sarah@sarahwintondesign.com
description: 'Graphic Designer in Birmingham, AL

'
tagline: Telling Stories and Creating Beauty
current-work:
  title: Current Work
  link: http://emilywellsdesign.com
contact-me:
  title: Contact Me
  link: mailto:sarah@sarahwintondesign.com
social:
  facebook: sarahwintondesign
  twitter: sarahwinton
  instagram: sarahwintondesign
  medium: sarahwinton
  linked-in: sarah-winton
  github: sarahwintondesign
plugins:
- jekyll-feed
baseurl: 
markdown: kramdown
