---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: heading
  label: Collections
- type: jekyll-pages
  label: Pages
  create: none
  templates:
  - pages
- type: directory
  path: _work
  label: Portfolio
  create: all
  match: "**/*"
  templates:
  - work
- type: heading
  label: Information
- type: document
  path: _data/info.yml
  label: Company
- type: document
  path: _config.yml
  label: Site
- type: document
  path: _data/theme.yml
  label: Theme
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
